package com.boardgamegeek.db.model

data class PlayLocal(
    val internalId: Long,
    val playId: Int?,
    val date: String,
    val objectId: Int,
    val itemName: String,
    val quantity: Int,
    val length: Int,
    val location: String?,
    val incomplete: Boolean,
    val noWinStats: Boolean,
    val comments: String?,
    val syncTimestamp: Long,
    val playerCount: Int?,
    val syncHashCode: Int?,
    val gameUpdatedPlaysTimestamp: Long?,
    val dirtyTimestamp: Long?,
    val updateTimestamp: Long?,
    val deleteTimestamp: Long?,
    val startTime: Long?,
    val gameImageUrl: String?,
    val gameThumbnailUrl: String?,
    val gameHeroImageUrl: String?,
    val gameIsCustomSorted: Boolean?,
    val players: List<PlayPlayerLocal>?,
)
