package com.boardgamegeek.entities

import com.boardgamegeek.provider.BggContract

data class CollectionItemForUploadEntity(
        val internalId: Long = BggContract.INVALID_ID.toLong(),
        val collectionId: Int = BggContract.INVALID_ID,
        val gameId: Int = BggContract.INVALID_ID,
        val collectionName: String = "",
        val imageUrl: String = "",
        val thumbnailUrl: String = "",
        val heroImageUrl: String = "",
        val rating: Double? = null,
        val ratingTimestamp: Long = 0L,
        val comment: String? = null,
        val commentTimestamp: Long = 0L,
        val acquiredFrom: String = "",
        val acquisitionDate: String = "",
        val privateComment: String = "",
        val currentValue: Double = 0.0,
        val currentValueCurrency: String = "",
        val pricePaid: Double = 0.0,
        val pricePaidCurrency: String = "",
        val quantity: Int? = null,
        val inventoryLocation: String = "",
        val privateInfoTimestamp: Long = 0L,
        val owned: Boolean = false,
        val previouslyOwned: Boolean = false,
        val forTrade: Boolean = false,
        val wantInTrade: Boolean = false,
        val wantToBuy: Boolean = false,
        val wantToPlay: Boolean = false,
        val preordered: Boolean = false,
        val wishlist: Boolean = false,
        val wishlistPriority: Int = 0,
        val statusTimestamp: Long = 0L,
        val wishlistComment: String? = null,
        val wishlistCommentDirtyTimestamp: Long = 0L,
        val tradeCondition: String? = null,
        val tradeConditionDirtyTimestamp: Long = 0L,
        val wantParts: String? = null,
        val wantPartsDirtyTimestamp: Long = 0L,
        val hasParts: String? = null,
        val hasPartsDirtyTimestamp: Long = 0L,
)